FROM python:3.10-slim

WORKDIR /app

# Outils de base + drivers Postgres
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
        curl && \
    rm -rf /var/lib/apt/lists/*

# Fichiers de dépendances
COPY requirements.txt /app/requirements.txt
COPY test/requirements.txt /app/requirements-test.txt

# Dépendances Python du projet + tests
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /app/requirements.txt && \
    pip install --no-cache-dir -r /app/requirements-test.txt

# On copie tout le code du repo (fraud_training.py, etc.)
COPY . /app

# Pytest va lancer notre test d'intégration de ré-entrainement
CMD ["pytest", "test/test_fraud_training.py", "-s", "-vv"]